
import Home from '../components/home';
import bg from '../public/images/wather-backgroand.jpg'
import Countries from './../components/Countries';
import Link from 'next/link';
import { useEffect, useState } from "react";


  
export default function Main() {
//  const [cities, setCities] = useState();

//   const [city, setCity] = useState("Yemen");

//   const handleClick = (name) => {
//     setCity(name);
//   };

//   const [weather, setWeather] = useState();
//   useEffect(() => {
//     fetch(
//       `http://api.weatherstack.com/current?access_key=1640ee92de401505fbf5c614c98c8de5&query=${city}`
//     )
//       .then((res) => res.json())
//       .then((res) => {
//         setWeather(res);
//       })
//       .catch((err) => console.error(err));
//     // console.log(weather);
//   }, [{city}]);

//   useEffect(() => {
//     fetch("https://countriesnow.space/api/v0.1/countries/capital/")
//       .then((res) => res.json())
//       .then((res) => {
//         setCities(res);
//       })
//       .catch((err) => console.error(err));
//   }, []);

//   // console.log(cities);

//   // setState("Not Aiman");
//   if (!cities) return <div>Loading...</div>;


  return (
    <div className="index">
      index
    </div>
    
    // <div className='body' style={{ backgroundImage: `url(${bg.src})`, }}>
    //     {/* <Link href={{
    //       pathname: './apiPages',
    //       query: weathers // the data
    //     }}>
    //     <a>Some text</a>
    //   </Link>   */}
      
    //     <title>Wather App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="" />
        
    //   <div className="cointainer" >
    //   {/* <h1>index</h1> */}
    //   <div className="col-9" ><Home  onClick={handleClick} city={cities}  weather={weather} /></div>
    //     {/* <div className="col-3"><Countries onClick={handleClick} city={cities} /></div> */}
    //   </div>
      
         
    // </div>
    
  )
}
