
import Home from '../components/home';
import bg from '../public/images/wather-backgroand.jpg'
import Countries from './../components/Countries';

export default function Main() {
  return (
    
      
    <div classNameName='body' style={{ backgroundImage: `url(${bg.src})`, }}>
         <title>Wather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
        
      <div className="cointainer" >
        <div className="col-9" ><Home/></div>
        <div className="col-3"><Countries/></div>
      </div>
      
         
    </div>
    
  )
}
